### ISSUE TITLE
Why the `fastq` files are `.f1 & .r2` rather than `.r1 & r2` ?

### ISSUE THREAD

**Issue by jiangpuxuan** [gangcai/zebTestis#1]
Hi,
I am interested in your fabulous work. But `cellranger-6.0.0` ran into the error that:
```
If your files came from bcl2fastq or mkfastq:
 - Make sure you are specifying the correct --sample(s), i.e. matching the sample sheet
 - Make sure your files follow the correct naming convention, e.g. SampleName_S1_L001_R1_001.fastq.gz (and the R2 version)
 - Make sure your --fastqs points to the correct location.
 - Make sure your --lanes, if any, are correctly specified.

```

Here is my code:

```
mytranscript=/Array-Tuqiang/pxjiang/genome.annotation.data/zebrafish_GRCz11_10x_transcriptome_ref/
cellranger count --id="drr_testis" \
                   --transcriptome=$mytranscript \
                   --fastqs=/Array-Tuqiang/pxjiang/pubdata/zebrafish_testis/rawdata/ \
                   --sample="drr_testis" \
                   --expect-cells=15000 \
                   --localcores=30 \
                   --localmem=64

```

Here are some of my `fastq` names:
<img width="403" alt="8322d41ddf32f3f380b2c076aa6651c" src="https://user-images.githubusercontent.com/81287604/165956538-43578fdf-2440-4fdc-8574-b8dadd9f89ab.png">

So, I wonder why the `fastq` files are `.f1 & .r2` rather than `.r1 & r2`.

Thank you for your help!

**Comment by gangcai** [comment]
The file names of raw sequencing data had been renamed by the NGDC database. For cellranger processing, you can rename the files for the convenience.

**Comment by gangcai** [comment]
One example for renaming:

CRR269885_f1.fastq.gz  --> CRR269885_R1_001.fastq.gz
CRR269885_r2.fastq.gz --> CRR269885_R2_001.fastq.gz

**Comment by Dana11T** [comment]
But according to the file size, f1 is greater than r2, shouldn't it be an R2 file

**Comment by Dana11T** [comment]
> One example for renaming:
> 
> CRR269885_f1.fastq.gz --> CRR269885_R1_001.fastq.gz CRR269885_r2.fastq.gz --> CRR269885_R2_001.fastq.gz

But according to the file size, f1 is greater than r2, shouldn't it be an R2 file

**Comment by gangcai** [comment]
> > One example for renaming:
> > CRR269885_f1.fastq.gz --> CRR269885_R1_001.fastq.gz CRR269885_r2.fastq.gz --> CRR269885_R2_001.fastq.gz
> 
> But according to the file size, f1 is greater than r2, shouldn't it be an R2 file

f1 file is smaller than r2 file. For example, the file size for CRR269885_f1.fastq.gz is 184.9 MB and the file size for CRR269885_r2.fastq.gz is 635.77 MB.  If you find your downloaded f1 file is greater than r2, please check the md5 to make sure it's downloaded correctly. The file sizes could also be found in the NGDC browser, for example, https://ngdc.cncb.ac.cn/gsa/browse/CRA003925/CRR269885.

**Comment by Dana11T** [comment]
In other data, there are indeed cases where the f1 file is larger than the r2 file, so I'm still not sure if f1 should be named R1.
![screenshot-1714986021699](https://github.com/gangcai/zebTestis/assets/133756898/61374051-53bd-4998-8dd3-3c479ff9f227)

**Comment by gangcai** [comment]
> In other data, there are indeed cases where the f1 file is larger than the r2 file, so I'm still not sure if f1 should be named R1.
> ![screenshot-1714986021699](https://private-user-images.githubusercontent.com/133756898/328128278-61374051-53bd-4998-8dd3-3c479ff9f227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDQwMjMsIm5iZiI6MTcxNTA0MzcyMywicGF0aCI6Ii8xMzM3NTY4OTgvMzI4MTI4Mjc4LTYxMzc0MDUxLTUzYmQtNDk5OC04ZGQzLTNjNDc5ZmY5ZjIyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMTAyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGZjNDg2N2YyMmExMjA5MWFiZDY1MTkzYTBmNmNkYjM1MDAyYWZjYjYwNDdkM2I2NWFjNzRhNzY2ZmI3YmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fFwxeM4iXgYmV68ly9sBQ_v0eOxY72aWVTWScKvpI70)

It seems that the data you mentioned belongs to other research group.

**Comment by Dana11T** [comment]
The R2 file is the true sequencing reads and should definitely be the largest file. So, in fact, the names of f1 and r2 can't be changed directly to R1 R2, right?

**Comment by Dana11T** [comment]
> > In other data, there are indeed cases where the f1 file is larger than the r2 file, so I'm still not sure if f1 should be named R1.
> > ![screenshot-1714986021699](https://private-user-images.githubusercontent.com/133756898/328128278-61374051-53bd-4998-8dd3-3c479ff9f227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDQwMjMsIm5iZiI6MTcxNTA0MzcyMywicGF0aCI6Ii8xMzM3NTY4OTgvMzI4MTI4Mjc4LTYxMzc0MDUxLTUzYmQtNDk5OC04ZGQzLTNjNDc5ZmY5ZjIyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMTAyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGZjNDg2N2YyMmExMjA5MWFiZDY1MTkzYTBmNmNkYjM1MDAyYWZjYjYwNDdkM2I2NWFjNzRhNzY2ZmI3YmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fFwxeM4iXgYmV68ly9sBQ_v0eOxY72aWVTWScKvpI70)
> 
> It seems that the data you mentioned belongs to other research group.

The R2 file is the true sequencing reads and should definitely be the largest file. So, in fact, the names of f1 and r2 can't be changed directly to R1 R2, right?

**Comment by gangcai** [comment]
> > > In other data, there are indeed cases where the f1 file is larger than the r2 file, so I'm still not sure if f1 should be named R1.
> > > ![screenshot-1714986021699](https://private-user-images.githubusercontent.com/133756898/328128278-61374051-53bd-4998-8dd3-3c479ff9f227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDQwMjMsIm5iZiI6MTcxNTA0MzcyMywicGF0aCI6Ii8xMzM3NTY4OTgvMzI4MTI4Mjc4LTYxMzc0MDUxLTUzYmQtNDk5OC04ZGQzLTNjNDc5ZmY5ZjIyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMTAyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGZjNDg2N2YyMmExMjA5MWFiZDY1MTkzYTBmNmNkYjM1MDAyYWZjYjYwNDdkM2I2NWFjNzRhNzY2ZmI3YmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fFwxeM4iXgYmV68ly9sBQ_v0eOxY72aWVTWScKvpI70)
> > 
> > 
> > It seems that the data you mentioned belongs to other research group.
> 
> The R2 file is the true sequencing reads and should definitely be the largest file. So, in fact, the names of f1 and r2 can't be changed directly to R1 R2, right?

In our data, you can directly make such changes to adapt to the cell ranger.
