### ISSUE TITLE
file clusterRename.tsv

### ISSUE THREAD

**Issue by RN-Taka** [gangcai/zebTestis#2]
Hi, i'm beginner in scRNAseq and trying to use your pipeline. whats is/Were is the file ClusterRename.tsv ?

thank you a lot

**Comment by gangcai** [comment]
This file can be created by the user according to their clustering annotation information. The basic format is (tab separated):
cluster_id     cluster_name
0                    SPG
1                     Leydig
......

**Comment by RN-Taka** [comment]
Thank you!!
